version: '3'
services:
  portainer:
    image: portainer/portainer:1.14.3
    networks:
      - spacely-eng
    ports:
      - 50443:9000
    volumes:
      - /nfs/docker-data/container-data/administration/portainer/data:/data
      - /nfs/docker-data/container-data/administration/portainer/certs:/certs:ro
    command: --ssl --sslcert /certs/server-cert.pem --sslkey /certs/server-key.pem
    deploy:
      labels:
        - portainer_service
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager, node.labels.cicdBuildsOnly != true]
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
networks:
  spacely-eng:
    external:
      name: spacely-eng-core
